複数モデル対応
aws-samples/generative-ai-use-cases-jp pull request #230
Opened 2023-12-11 09:42 UTC by maekawataiki

*Issue #, if available:*
#113 

*Description of changes:*
- Bedrock モデル（Claude、Claude Instant、Stable Diffusion）および SageMaker モデルの複数モデル選択に対応
- 仕様変更
  - アプリケーションの変更
    - ドロップダウンから事前定義された Bedrock と SageMaker の複数のモデルを選択可能となった
    - テキストは Claude v2 と Claude Instant v1 と SageMaker モデル、画像は Stable Diffusion と Titan Image に対応
  - デプロイ手順の変更
    - `modelType` と `modelName` でモデル指定 → Bedrock は `modelNames`と`imageGenerationModelNames` 、SageMaker は`endpointNames` でカンマ区切りで複数モデル指定可能
    - `promptTemplate` でプロンプトテンプレート指定 → Bedrock モデル名もしくは SageMaker エンドポイント名で自動でプロンプトテンプレートを判断
    - フロントエンドに環境変数としてモデル情報を渡すためコマンドラインではなく `cdk.json` でのパラメータ変更を推奨

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-12 05:09 UTC, tbrand commented on docs/DEPLOY_OPTION.md
> +注：画像生成は現状 ap-northeast-1 では利用できません。
ここと直接関係ないのですが、Titan の画像生成がこの PR からサポートされていると思います。それに伴い「画像生成の有効化」の章を正しく書き直すか、一旦 Titan のサポートは見送るか、整合性をとってください。

2023-12-13 07:06 UTC, tbrand commented on packages/web/src/hooks/useModel.ts
> +);
すいません、',' で split する仕様ですが、こちらは json array に変更していただけますでしょうか？:pray:
最近マージしたこちらに合わせたいです！
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/232/files#diff-cc3c0362feef1a867047fb9e6e3c5ff8761730eabd485f4865b4679278cfc485R170

2023-12-14 07:38 UTC, maekawataiki commented on packages/cdk/cdk.json
> +    "ragEnabled": true,
失礼しました、戻し忘れていました。

2023-12-14 07:38 UTC, maekawataiki commented on packages/cdk/lambda/predictTitle.ts
> +};
パラメータで渡したモデルの中から最初の Claude モデルを利用することにしました。

2023-12-14 07:38 UTC, maekawataiki commented on packages/cdk/lambda/utils/bedrockApi.ts
>  };
修正しました

2023-12-14 07:39 UTC, maekawataiki commented on packages/cdk/lambda/utils/promptTemplates.ts
> +};
修正しました

2023-12-14 07:39 UTC, maekawataiki commented on packages/cdk/cdk.json
> +    "imageGenerateModelNames": "stability.stable-diffusion-xl-v0,amazon.titan-image-generator-v1",
修正しました。一旦 cluade v2  と stable diffusion をデフォルトにしました。

2023-12-14 07:39 UTC, maekawataiki commented on packages/cdk/lib/construct/api.ts
> +    if (endpointNames !== undefined) {
修正しました

2023-12-14 07:39 UTC, maekawataiki commented on packages/web/src/hooks/useModel.ts
> +);
ありがとうございます。確かにそうですね。修正しました。

2023-12-14 07:39 UTC, maekawataiki commented on packages/web/src/pages/ChatPage.tsx
> +          </SelectField>
修正しました！

2023-12-14 07:39 UTC, maekawataiki commented on packages/web/src/pages/Setting.tsx
> +  const modelRegion = import.meta.env.VITE_APP_REGION;
失礼しました。修正しました。

2023-12-14 07:39 UTC, maekawataiki commented on packages/web/src/prompts/index.ts
> +};
そうですね。画像生成はデプロイ時に渡されたパラメータでいいですね。
ユーズケースも将来的に複数モデルのプロンプトのメンテは大変になりそうなので少なくとも現時点では Claude に限定してしまってもいいかもしれません。一元管理するようにします。

2023-12-14 07:39 UTC, maekawataiki commented on docs/DEPLOY_OPTION.md
>  ```
-c ではなく cdk.json で設定を変更することを推奨する旨追加しました。

2023-12-14 07:39 UTC, maekawataiki commented on docs/DEPLOY_OPTION.md
> +注：画像生成は現状 ap-northeast-1 では利用できません。
画像生成の有効化の章は消して Amazon Bedrock のモデル選択についての章に統合しモデルの有効化についての説明はそちらに寄せました。

2023-12-14 07:41 UTC, maekawataiki commented on packages/web/src/pages/ChatPage.tsx
> +          </SelectField>
修正しました

2023-12-15 02:31 UTC, tbrand requested changes
## モデル名のハードコードについて

最終的に以下の形にしてください！どうしてもそうできない場合は教えてくださいませ！
- 'anthropic.claude-v2' と言ったモデルのハードコーディングはプロジェクト全体で 1 箇所のみ (ただし `cdk/lib/constructs/api.ts` でデフォルトのモデルを指定する箇所は除く)
- デフォルトのモデルを選択する、という場合は cdk.json に書かれているモデルの先頭のものを選択

## cdk.json の仕様について

今カンマ区切りで複数のモデルを指定する方式にしていますが、これを json array に変更お願いします！(前回コメントしたつもりでしたが、漏れたかもしれません。すいません。)
string で json array を渡した場合は JSON.parse で戻してください！
これは昨日マージした https://github.com/aws-samples/generative-ai-use-cases-jp/pull/232 の仕様に合わせたものです！

## supportedModels について

`prompts/index.ts` で定義されている supportedModels について少し整理したいです。今の所 2 つの役割があるのかなと理解しています。

1. ユースケースごとにサポートされているモデルが異なる場合に調整できる
2. モデル名の打ち間違いがあった時に Select の選択肢から消える

まず (1) については、現状不要だと思っています。将来的に必要になるケースはあるのでしょうか？
次に (2) については、こちらは別のレベルで対応するべきだと思います。例えば cdk deploy 時に落としてくれると一番嬉しいですよね。(それができるかは置いておいて)
cdk で落ちないってことは、lambda や web などでモデル名が間違っていないかチェックする必要が原則なくなるという理解です。
今 `packages/cdk/lambda/utils/models.ts` に定義されている `BEDROCK_MODELS` とか `BEDROCK_IMAGE_GEN_MODELS` を別ファイルに切り出して、lambda、cdk、web 等から
参照できるようにすると良いのですかね？今の types みたいに。いいアイデアがあれば教えてください。

## その他

README.md にデプロイオプションの全ての章のアンカーがハードコーティングされているので、そちらも修正をお願いします！

2023-12-15 02:31 UTC, tbrand commented on packages/cdk/lambda/utils/bedrockApi.ts
> +  model: string,
もしかしたら複雑性が増すかもしれませんが、本来はこちらの `model: string` が `model: keyof typeof BEDROCK_MODELS` であるべきだと思いました。こちらは変更可能でしょうか？(bedrockApi.ts の他の箇所も同様)

2023-12-15 02:31 UTC, tbrand commented on packages/web/src/hooks/useModel.ts
> +};
全体コメントでも書かせていただきますが、カンマ区切りから json array に変更していただけるとありがたいです...！

2023-12-15 02:31 UTC, tbrand commented on packages/web/src/pages/Setting.tsx
> +    .join(', ');
細かくて恐縮ですが、useModels から引っ張れると良いと思います！実際に使うモデルと整合性ずれることがないため。

2023-12-15 06:10 UTC, maekawataiki commented on docs/DEPLOY_OPTION.md
> +注：画像生成は現状 ap-northeast-1 では利用できません。
説明を追加しました。
Titan はサポートされています。ユーザーが指定したモデルはユーザーがモデルの有効化を確認するという説明に含有することにしました。

2023-12-15 06:10 UTC, maekawataiki commented on packages/web/src/hooks/useModel.ts
> +);
すみません、漏れてました。JSON Array に修正しました

2023-12-15 06:10 UTC, maekawataiki commented on packages/cdk/lambda/predictTitle.ts
> +};
修正しました。

2023-12-15 06:11 UTC, maekawataiki commented on packages/cdk/lambda/predictTitle.ts
> +    console.log(model);
消し忘れでした。修正しました。

2023-12-15 06:11 UTC, maekawataiki commented on packages/web/src/hooks/useChat.ts
> +      },
修正しました。

2023-12-15 06:11 UTC, maekawataiki commented on packages/web/src/hooks/useImage.ts
> +      }
修正しました

2023-12-15 06:11 UTC, maekawataiki commented on packages/web/src/hooks/useRag.ts
> +      }
修正しました

2023-12-15 06:14 UTC, maekawataiki commented on packages/web/src/prompts/index.ts
> +const useCaseModels = filterTextModels(useCaseModelNames);
修正しました
supportedModels についてなのですが、現状 Claude 以外のモデル（SageMaker モデルや将来的に Titan など）を利用した際にプロンプトを変更する拡張性を追加するためにモデルでプロンプトを切り替えられる仕様にしていました。カスタマイズが前提なので今は一旦カスタマイズできる拡張性を残しつつ useCaseModels は textModels に統合します。

2023-12-15 06:14 UTC, maekawataiki commented on packages/cdk/lambda/utils/bedrockApi.ts
> +  model: string,
これは BEDROCK_MODELS の型定義を修正することでなくしました。

2023-12-15 06:14 UTC, maekawataiki commented on packages/web/src/hooks/useModel.ts
> +};
修正しました

2023-12-15 06:14 UTC, maekawataiki commented on packages/web/src/pages/Setting.tsx
> +    .join(', ');
修正しました

2023-12-15 07:35 UTC, tbrand requested changes
かなり simplify していただきましたが、まとめるとモデルを追加する時に変更するファイルは以下の 2 点で間違い無いでしょうか？ (prompt template は考慮しない)
- packages/cdk/lib/construct/api.ts
- packages/cdk/lambda/utils/models.ts

2023-12-15 07:35 UTC, tbrand commented on docs/DEPLOY_OPTION.md
> +CDK の context は '-c' でも指定できますが、その場合コードベースに変更が入らずフロントエンドのビルドが実施されないため、このアセットに関しては全ての設定は cdk.json の設定を変更することを推奨します。
ここ太文字でお願いします！

2023-12-15 07:35 UTC, tbrand commented on docs/DEPLOY_OPTION.md
> +注：Stable Diffusion および Titan Image が未対応なため、画像生成は現状 ap-northeast-1 では利用できません。
太文字にする、かつ前段に「UI上は表示されますが」と追記してください！

2023-12-15 07:35 UTC, tbrand commented on packages/web/src/prompts/index.ts
> +    if (modelNames.includes(modelName)) {
(他の箇所も同様です)

## 前提
`modelNames.includes(modelName)` が false の場合に `Unsupported Model` が throw されると思うのですが、`supportedModels` は `textModels` とずれている (≠ `modelNames`) の理解が難しかったです。

## 対応方針
ここはシンプルな対応をお願いしたいです。`supportedModels` という property は全て削除して、各ページの availableModels は textModels を使えば良いのではないでしょうか？それに加え `if (modelsNames.includes(modelName))` のチェックも外してしまってはどうでしょう。そうすると Titan でも SageMaker でも xml 形式のプロンプトが飛ぶことになりますが、おそらく Frontend が `unsupported model`　でエラーになるという状況よりはデバッグが楽だと思います。この対応で一番厳しくなるのは claude も titan も sagemaker も同時に使いたいという人だと思いますが、そこまでカバーする必要はないです。

2023-12-15 07:35 UTC, tbrand commented on packages/web/src/pages/RagPage.tsx
> +        )}
おそらくバナーがかぶっていてチャットを始めるまでモデル選択が見えません！モデルが複数ある時はバナーの位置を下げてもらえると！

2023-12-15 11:31 UTC, maekawataiki commented on packages/web/src/pages/RagPage.tsx
> +        )}
修正しました！

2023-12-15 11:31 UTC, maekawataiki commented on packages/web/src/prompts/index.ts
> +    if (modelNames.includes(modelName)) {
修正しました。

2023-12-15 11:31 UTC, maekawataiki commented on docs/DEPLOY_OPTION.md
> +注：Stable Diffusion および Titan Image が未対応なため、画像生成は現状 ap-northeast-1 では利用できません。
修正しました

2023-12-15 11:31 UTC, maekawataiki commented on docs/DEPLOY_OPTION.md
> +CDK の context は '-c' でも指定できますが、その場合コードベースに変更が入らずフロントエンドのビルドが実施されないため、このアセットに関しては全ての設定は cdk.json の設定を変更することを推奨します。
修正しました

2023-12-15 11:32 UTC, maekawataiki commented on packages/web/src/hooks/useModel.ts
> +};
ありがとうございます。prompts/index.ts から消したのでもう使用しないですね。削除します。

2023-12-15 11:32 UTC, maekawataiki commented on packages/cdk/lambda/predictStream.ts
> +      event.model || defaultModel,
すみません、これは修正時に漏れたものです。

2023-12-15 11:34 UTC, maekawataiki commented
モデルを追加時に必要なのは
- packages/cdk/lib/construct/api.ts (デプロイ時のバリデーション）
- packages/cdk/lambda/utils/models.ts (モデルの実装)
ですね。

2023-12-18 02:29 UTC, tbrand reviewed
コード的には LGTM です！:+1: 何往復もしてしまいすみませんでした！:pray:
あとはドッグフーディングお願いして、皆さんから OK 出たら私がマージしますね！

2023-12-19 06:45 UTC, merged