RAG のデータソースの Footnote 化
aws-samples/generative-ai-use-cases-jp pull request #231
Opened 2023-12-12 01:40 UTC by maekawataiki

*Issue #, if available:*
#131 

*Description of changes:*
- RAG のデータソースの URL を LLM に生成させるのではなく、Markdown の Footnote 化 を使用してデータソースを参照するようにする。これにより Hallucination が削減され、生成トークン数とレイテンシーも減る。

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-12 07:45 UTC, wadabee requested changes
脚注のリンクをクリックすると別タブが開くので、以下のファイルの修正をお願いします！
現在は一律で`target="_blank"`を指定していますが、脚注のリンクの場合はこれを設定しないようにする必要があります（同一ホストだったらという判断で良さそう）
また、アンカーリンクで移動するために、idの設定も必要なので`props.id`もaタグに設定するようにお願いします！
`packages/web/src/components/Markdown.tsx`

2023-12-12 12:29 UTC, maekawataiki commented on packages/web/src/prompts/index.ts
> +      // DocumentURI: item.DocumentURI,
修正しました

2023-12-12 12:31 UTC, maekawataiki commented
`target="_blank"` については href が # から始まるためそれで判断することにしました。id も付与しました。
追加で同一ページで複数の RAG の応答があると id が重複することがあるためチャットの応答の idx を prefix にしました。

2023-12-12 12:33 UTC, maekawataiki commented
あと footer 付与すると2回目以降の応答で Few-shot で参考にしてしまうため、リクエスト前の前処理で footer を除去して LLM に与える処理を追加しました。

2023-12-13 05:49 UTC, wadabee approved these changes
LGTM!!

2023-12-13 05:49 UTC, merged