feat: system context save feature
aws-samples/generative-ai-use-cases-jp pull request #416
Opened 2024-03-22 08:27 UTC by Calic0Cat

*Issue #281 , if available:*

*Description of changes:*
- チャットのシステムコンテキストを保存する機能を追加
- Prompt List の最下部に自身が作成したシステムコンテキストを表示する機能を追加

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-25 01:55 UTC, tbrand commented on packages/web/src/prompts/index.ts
> +}[];
ここの方定義は API のレスポンスの方としても使われるので types に定義されているべきだと思いました！また、SystemContextList の title って何に使われていますか？Lambda 内で "システムコンテキスト" という文字がハードコーディングされているだけのように見えましたので、不要かと思いました。そういう意味ではレスポンスがネストされている意味も特にないのかなと思いました。

before: { items: systemContextListItem[] }
after: systemContextListItem[]

2024-03-25 12:42 UTC, Calic0Cat commented on packages/web/src/prompts/index.ts
> +}[];
レビューありがとうございます！
修正しました！

2024-03-26 01:45 UTC, tbrand requested changes
- sendIconEnabled のバグの影響だと思いますが、現状は「システムコンテキストを保存せずに変更する」ということができませんよね？これはデグレです。
- 「プロンプト例」の中に「システムコンテキスト」があるのが不自然という指摘が直っていないです！「プロンプト例」と同じように「システムコンテキスト」を扱ってください！また「システムコンテキスト」だけだと意味が伝わらないと思うので、「保存したシステムコンテキスト」等にしてください！

2024-03-26 01:45 UTC, tbrand commented on packages/cdk/lambda/listSystemContexts.ts
> +import { SystemContextListItem } from 'generative-ai-use-cases-jp/src/systemContext';
他の箇所と同じように import { SystemContextListItem } from 'generative-ai-use-cases-jp'  で import できるようにしてください！src/index.d.ts で export すればいけるはずです。

2024-03-26 01:45 UTC, tbrand commented on packages/web/src/pages/ChatPage.tsx
> +        />
これは用途が違うので、ここでは使わないでください！普通に textarea 等を利用してください！用途はコンポーネント名 (Input "Chat" Content) に合わせてください！また、増やした sendIconEnabled props は削除してください！

2024-03-26 01:45 UTC, tbrand commented on packages/web/src/pages/ChatPage.tsx
> +  const [loadingList, setLoadingList] = useState<number | undefined>();
これは何ですか？loadingList という名前から型が number であるので、用途がパッとみてわからないです！変数名の変更か、実装の変更をお願いしたいです！おそらく delete した時に各項目をローディングをするために使われていると思いますが、楽観的削除で良いです。(UI から先に削除して API の削除はバックグラウンドで行う。API の削除は成功することを前提として良い) 他の箇所もそうしています。

2024-03-26 01:45 UTC, tbrand commented on packages/web/src/components/InputChatContent.tsx
> +        )}
いずれにせよ sendIconEnabled は削除していただきますが、sendIconEnabled が false の時に sendIcon が有効化されているのは名前と反しているとおもます！

2024-03-27 09:55 UTC, Calic0Cat commented on packages/cdk/lambda/listSystemContexts.ts
> +import { SystemContextListItem } from 'generative-ai-use-cases-jp/src/systemContext';
ありがとうございます！修正しました！

2024-03-27 09:56 UTC, Calic0Cat commented on packages/web/src/pages/ChatPage.tsx
> +        />
systemContextTitle と同じく、Textarea で対応しました！

2024-03-27 09:56 UTC, Calic0Cat commented on packages/web/src/pages/ChatPage.tsx
> +  const [loadingList, setLoadingList] = useState<number | undefined>();
ありがとうございます！
楽観的削除として実装を修正しました！

2024-03-27 09:57 UTC, Calic0Cat commented on packages/web/src/components/InputChatContent.tsx
> +        )}
レビューありがとうございます！修正しました！

2024-04-02 06:04 UTC, tbrand commented on packages/web/src/utils/SystemContextUtils.ts
> +};
実装が chatId と全く同じだと思うので、decomposeChatId を decomposeId とかに rename して使いまわした方が良いと思います！

2024-04-02 08:15 UTC, tbrand commented on packages/web/src/components/PromptList.tsx
> +  onClickDeleteSystemContext: (params: string, index: number) => void;
ここは引数の名前が params ではないですよね？

2024-04-02 08:58 UTC, Calic0Cat commented on packages/web/src/utils/SystemContextUtils.ts
> +};
レビューありがとうございます！使い回すように変更しました！

2024-04-02 08:58 UTC, Calic0Cat commented on packages/web/src/components/PromptList.tsx
> +  onClickDeleteSystemContext: (params: string, index: number) => void;
修正しました！

2024-04-02 08:59 UTC, Calic0Cat commented on packages/web/src/prompts/index.ts
> +};
レビューありがとうございます！
使い回す形で修正しました！

2024-04-02 08:59 UTC, Calic0Cat commented on packages/web/src/pages/ChatPage.tsx
> +      );
レビューありがとうございます！
indexを取得する形に変更しました！

2024-04-02 09:00 UTC, Calic0Cat commented on packages/web/src/components/PromptList.tsx
> +                    key={`${i}`}
ありがとうございます！
不要でした :pray:

2024-04-03 01:28 UTC, tbrand commented on packages/cdk/cdk.json
> +    "dashboard": true,
cdk.json がコミットされています！

2024-04-03 02:26 UTC, Calic0Cat commented on packages/cdk/cdk.json
> +    "dashboard": true,
ご指摘ありがとうございます 🙏 
修正しました！

2024-04-03 06:07 UTC, tbrand approved these changes

2024-04-03 06:07 UTC, merged