別アカウントの Bedrock を利用するためのクロスアカウント設定を追加
aws-samples/generative-ai-use-cases-jp pull request #444
Opened 2024-04-08 07:56 UTC by tomachi1201

## 目的
Bedrock サービスのみ、別の AWS アカウントを指定して構成する

## 利用条件
- Bedrock 用 AWS アカウント で IAM Role を手動で作成しておく
- 作成した IAM Role を cdk.json に手動で書く

## 修正内容
- packages/cdk/cdk.json
  - roleArn と sessionName を追加した。
  - roleArn に "arn:aws:iam::アカウントID:role/ロール名" を指定することにより、別の AWS アカウント上の Bedrock サービスを利用できるようになる。
  - sessionName にはデフォルト値を設定済みである。

- packages/cdk/lib/construct/api.ts
  - 上記を Lambda 環境変数に設定する
  - roleArn が指定されている場合に AssumeRole 用のポリシーを設定

- packages/cdk/lambda/utils/bedrockApi.ts
  - roleArn が設定されている場合に AssumeRole する

## 動作確認
- cdk デプロイできることを確認した
- ユースケース一覧が動作することを確認した
- roleArn 設定時に Bedrock アカウントのみ、トークン数などが増えていることを CloudWatch Metrics から確認した
- roleArn 非設定時に アプリケーションデプロイ用アカウントのみ、トークン数などが増えていることを CloudWatch Metrics から確認した

2024-04-08 08:15 UTC, tbrand requested changes
いくつかコメントさせていただきました！

別のAWSアカウントでRoleを作成して cdk.json に設定するまでの手順を https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/DEPLOY_OPTION.md に追加をお願いします！:pray: おそらく利用頻度としては低いオプションになると思うので、追加位置は最下部で問題ありません！また、手動で作成する手順を説明するにあたって、スクリーンショットなどは必要ありません！追加後に、DEPLOY_OPTION.md の他の項目と同様 README.md にアンカーリンクを追加してください！

また、念のためですが、ルートディレクトリにて `npm run lint` を実行していただけますでしょうか？:pray: (すでに実行されていたらすいません！)

2024-04-08 08:15 UTC, tbrand commented on packages/cdk/cdk.json
> +    "sessionName": "BedrockApiAccess",
roleArn と sessionName では項目名が一般用語すぎて、混乱を招く可能性があります！`crossAccountBedrock` 等の prefix をつけていただけないでしょうか？(長くなってしまっても良いです！) あと、sessionName は個別に設定したいケースがあるのでしょうか？もし、ない (あるいは極めて稀) のであれば、どこかに BedrockApiAccess をハードコーディングしてしまっても良いと思いました。設定項目は少ない方が嬉しいので！

2024-04-08 08:15 UTC, tbrand commented on packages/cdk/lambda/utils/bedrockApi.ts
> +// STSから一時的な認証情報を取得する関数を追加
「を追加」はコメントとして不要かと思います！

2024-04-08 08:15 UTC, tbrand commented on packages/cdk/lambda/utils/bedrockApi.ts
> +// BedrockRuntimeClientを初期化する関数
もう少しがっつり丁寧に説明したいです。事情を知らずにこの関数を見た人が混乱しないように。「本来はただ BedrockRuntimeClient を初期化すれば良いのだが、別のAWSアカウントのBedrockを利用したいというケースに限ってAssumeRoleして取得したcredentialで初期化する」といった趣旨のコメントを残していただけないでしょうか？

2024-04-10 17:21 UTC, tomachi1201 commented on packages/cdk/cdk.json
> +    "sessionName": "BedrockApiAccess",
crossAccountBedrockRoleArn としました。
sessionName については削除しハードコーディングしました。

2024-04-10 17:21 UTC, tomachi1201 commented on packages/cdk/lambda/utils/bedrockApi.ts
> +// STSから一時的な認証情報を取得する関数を追加
はい、「を追加」を削除しました。

2024-04-10 17:23 UTC, tomachi1201 commented on packages/cdk/lambda/utils/bedrockApi.ts
> +// BedrockRuntimeClientを初期化する関数
以下の通りにコメントを残しております。
```typescript
// BedrockRuntimeClient を初期化するこの関数は、通常では単純に BedrockRuntimeClient を環境変数で指定されたリージョンで初期化します。
// 特別なケースとして、異なる AWS アカウントに存在する Bedrock リソースを利用したい場合があります。
// そのような場合、CROSS_ACCOUNT_BEDROCK_ROLE_ARN 環境変数が設定されているかをチェックします。(cdk.json で crossAccountBedrockRoleArn が設定されている場合に環境変数として設定される)
// 設定されている場合、指定されたロールを AssumeRole 操作によって引き受け、取得した一時的な認証情報を用いて BedrockRuntimeClient を初期化します。
// これにより、別の AWS アカウントの Bedrock リソースへのアクセスが可能になります。
const initBedrockClient = async () => {
```

2024-04-10 17:32 UTC, tomachi1201 commented
> 別のAWSアカウントでRoleを作成して cdk.json に設定するまでの手順を https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/DEPLOY_OPTION.md に追加をお願いします！:pray: おそらく利用頻度としては低いオプションになると思うので、追加位置は最下部で問題ありません！また、手動で作成する手順を説明するにあたって、スクリーンショットなどは必要ありません！追加後に、DEPLOY_OPTION.md の他の項目と同様 README.md にアンカーリンクを追加してください！
→対応しましたのでご確認頂ければと思います。

> また、念のためですが、ルートディレクトリにて npm run lint を実行していただけますでしょうか？:pray: (すでに実行されていたらすいません！)
→すみません、こちら実行していなかったので実行致しました。

コメント頂いた内容を修正したものをアップしておりますのでご確認をお願い致します。

2024-04-11 06:50 UTC, tbrand requested changes

2024-04-11 06:50 UTC, tbrand commented on packages/cdk/cdk.json
> +    "ragEnabled": true,
不要なコミットが入っています！

2024-04-11 06:50 UTC, tbrand commented on packages/cdk/cdk.json
> +    "crossAccountBedrockRoleArn": "",
今までの設定項目と統一して、利用しない場合のデフォルト値を null にしていただいても良いでしょうか？

2024-04-11 13:02 UTC, tomachi1201 commented on packages/cdk/cdk.json
> +    "ragEnabled": true,
すみません、修正します！

2024-04-11 13:08 UTC, tomachi1201 commented on packages/cdk/cdk.json
> +    "crossAccountBedrockRoleArn": "",
null に変更後に再デプロイしたところ、以下のエラーが出力されたのですが、Lambda の環境変数には null は設定できないと理解しました。（認識齟齬ございましたらご指摘ください）
------------------------------
nerativeAiUseCasesStack failed: Error [ValidationError]: [/Resources/APIPredict09E4E4FF/Type/Environment/Variables/CROSS_ACCOUNT_BEDROCK_ROLE_ARN] 'null' values are not allowed in templates
------------------------------
そのため、空文字列 "" をデフォルト値とできればと思いますが如何でしょうか。
もしくは、null 値の場合、環境変数自体を設定しないように修正した方が良いでしょうか。

2024-04-12 00:16 UTC, tbrand commented on packages/cdk/cdk.json
> +    "crossAccountBedrockRoleArn": "",
すみません改めて確認したら全て null というわけではなく空文字もちょくちょく使っていたので、空文字で大丈夫です！:pray:

2024-04-12 08:56 UTC, tbrand approved these changes
LGTM！ありがとうございます！

2024-04-12 08:58 UTC, merged