画像生成ユーズケースの改善（解像度, 類似画像生成改善)
aws-samples/generative-ai-use-cases-jp pull request #508
Opened 2024-05-31 17:27 UTC by maekawataiki

*Issue #, if available:*
- #162, #404
- #507 
- #332 

*Description of changes:*
- 類似画像生成をワンクリックでできるボタンの追加
- Titan Image の similarityStrength パラメータの対応
- 解像度の変更
- リファクタリング

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-31 17:32 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +                  max={50}
SDXL1.0 の Step の最大が 50 のため修正

2024-05-31 17:32 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +                {generationMode === 'IMAGE_VARIATION' && (
IMAGE_VARIATION 時のみ利用するパラメータのため修正

2024-05-31 17:32 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +                  {generationMode !== 'TEXT_IMAGE' && (
IMAGE_VARIATION 時のみ必要なため Text to Image の時は非表示

2024-05-31 17:32 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +                  label="GenerationMode"
画像を選択していないときは暗黙的に Image Variation になっていたものを
Text to Image か Image to Image かわかりやすいようにドロップダウンで選択

2024-05-31 17:32 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +            <Button
選択した画像を Image Variation に送るためのボタン

2024-05-31 17:32 UTC, maekawataiki commented on packages/types/src/image.d.ts
> +  maskMode?: 'INPAINTING' | 'OUTPAINTING';
Inpaint / Outpaint はこの PR ではまだ実装しないが実装に向けて型だけドキュメントと合わせる

2024-06-03 03:13 UTC, wadabee requested changes

2024-06-03 03:13 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
> +            <Button
`Shuffle`のアイコンは一般的に使われているため、このボタンを押すことで類似画像を生成することを想像しづらいかなと思いました。
`tray-arrow-down` や `arrow-square-down` はいかがでしょうか？（インポートする感が出る気もしますが。。）

2024-06-03 03:13 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
> +              onClick={generateImageVariant}>
クリックしたタイミングで「詳細なパラメータ」を開いた方がわかりやすいかなと思いました。
画面上で変化がないので、初見だと何が起きているのかわからないと思います。

`ExpandableField`の修正が必要になりますが、外部から`expanded`のパラメータ（とそのdispatch）を任意で渡せるようにする必要がありそうです。

2024-06-03 05:33 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +              onClick={generateImageVariant}>
ありがとうございます。修正しました。

2024-06-03 05:34 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +            <Button
ありがとうございます。矢印だとダウンロード感が出るので画像編集のニュアンスを示せる PiNotePencil に変更しました。またホバーした時にヒントが出るように button に title をつけました。

2024-06-03 07:36 UTC, wadabee commented on packages/web/src/components/ExpandableField.tsx
> +  expanded?: number;
ここがnumberなのは、どういった理由でしょうか？
`boolean`ではダメですかね？

2024-06-03 07:36 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
>              </Button>
細かくくて恐縮ですが、画像が生成されていないときは`disabled`にするようにお願いします！
（押しても何も起こらない、という状態を解消するため）

2024-06-03 09:05 UTC, maekawataiki commented on packages/web/src/components/ExpandableField.tsx
> +  expanded?: number;
boolean だと true から true に変更された際 useEffect がトリガーされないため number にしていましたが子コンポーネントから親コンポーネントの expanded を更新できるように実装を変更しました。

2024-06-03 09:05 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
>              </Button>
ありがとうございます。対応しました。

2024-06-04 09:34 UTC, wadabee approved these changes
LGTM!!

2024-06-04 09:34 UTC, merged