ウェブサイト生成のユースケース
aws-samples/generative-ai-use-cases-jp pull request #511
Opened 2024-06-03 09:17 UTC by daisuke-awaji

*Description of changes:*

* 新規にウェブサイト生成のユースケースを実装しました。※ これは Experimental な試みです。
  * LLM から受け取った HTML, CSS, JavaScript を iframe に流し込んでリアルタイムにプレビューができます
  * チャットによる対話的な UI によって、ウェブサイトを修正できます。
  * マルチモーダルに対応しており、画像を入力としてウェブサイトを生成できます。
 
以下は出力のイメージです。
<img src="https://github.com/aws-samples/generative-ai-use-cases-jp/assets/20736455/db95411c-3490-448f-8112-714ea83dc47f" width="340px"> <img src="https://github.com/aws-samples/generative-ai-use-cases-jp/assets/20736455/345e85da-007a-408e-b866-ac176e454ee1" width="340px">

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-03 11:04 UTC, wadabee requested changes

2024-06-03 11:04 UTC, wadabee commented on packages/web/src/pages/summit/GenerateUIPage.tsx
> +              />
Streaming Responseの影響で画面がチラつくので、loading中はWebアプリを表示しない方が良いかなと思いました！

2024-06-03 11:04 UTC, wadabee commented on packages/web/src/pages/summit/GenerateUIPage.tsx
> +                      className="h-36 w-1/6 cursor-pointer">
以下のように履歴が重なって表示されているので、調整をお願いします！
<img width="492" alt="image" src="https://github.com/aws-samples/generative-ai-use-cases-jp/assets/52243855/0d01d8f5-0daa-4d5f-94cc-119a907e98cd">

2024-06-03 12:33 UTC, daisuke-awaji commented on packages/web/src/pages/summit/GenerateUIPage.tsx
> +              />
ある程度リアルタイムに描画された方が体験がいい（デモ映えする）と考えてます。
ので、debounce 処理を挟んでチラつき度合いを抑えてみようと思います。

2024-06-04 01:05 UTC, wadabee approved these changes
LGTM!

2024-06-04 01:06 UTC, merged