画像生成ユーズケースの Inpaint / Outpaint の対応
aws-samples/generative-ai-use-cases-jp pull request #513
Opened 2024-06-04 13:12 UTC by maekawataiki

*Issue #, if available:*
- #248 

*Description of changes:*
- Inpaint / Outpaint の対応

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-05 02:44 UTC, wadabee requested changes

2024-06-05 02:44 UTC, wadabee commented on packages/web/src/components/SketchPad.tsx
> +                    help="ペンのサイズ"
ここはhelpがなくても良いと思いました！

2024-06-05 02:44 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
> +          backgroundBase64={initImageBase64}
既存の問題ですが、一度閉じると背景画像が真っ白になってしまいます。
簡単に直せそうだったら、修正をお願いしますmm
もし難しそうだったら、別PRで対応します！

2024-06-05 02:44 UTC, wadabee commented on packages/web/src/components/Textarea.tsx
> +        disabled={props.disabled}
見た目で無効化されているか判断がつかないので、disabledの場合は背景色に薄いグレーの設定をお願いします！

2024-06-05 02:44 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
> +        title="マスク画像の設定"
コメントの位置が適当ですが・・・
前回のPRで作成した初期画像設定ボタンを押すと「IMAGE_VARIATION」が自動で選択されますが、「INPRINT」と「OUTPRINT」が選択されている場合は、そのままで良いかなと思いました！

2024-06-05 02:44 UTC, wadabee commented on packages/web/src/pages/GenerateImagePage.tsx
> +                        マスク画像
コメント位置が適当ですが・・・
「初期画像」が設定されていないと、INPRINTとOUTPRINTが機能しないと思います。
初期画像が必須であることがわかるように修正をお願いします！

以下、修正案
- 初期画像のラベルを「【必須】初期画像」のようにする
  - 未設定の場合は、生成ボタンを押せないようにしてもいいかも
- 一般的なバリデーションエラーのように、初期画像の部分にエラーメッセージを表示する（レイアウト的に対応しづらそう）
- 生成ボタンを押した際に、エラーメッセージかダイアログを表示する（UX的に良くないかも？）

2024-06-05 08:22 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +          backgroundBase64={initImageBase64}
修正しました！

2024-06-05 08:22 UTC, maekawataiki commented on packages/web/src/components/Textarea.tsx
> +        disabled={props.disabled}
ありがとうございます。修正しました

2024-06-05 08:22 UTC, maekawataiki commented on packages/web/src/pages/GenerateImagePage.tsx
> +                        マスク画像
ありがとうございます。未設定の場合は、生成ボタンを押せないようにする実装にしました

2024-06-06 00:21 UTC, wadabee requested changes

2024-06-06 00:21 UTC, wadabee commented on packages/web/src/components/SketchPad.tsx
>      canvasRef.current?.clear();
クリア時にCanvasもクリアするように修正をお願いします！
（未入力チェックが正しく動きません）

2024-06-06 00:21 UTC, wadabee commented on packages/web/src/components/SketchPad.tsx
> +    // }
消し忘れがあります！

2024-06-06 01:06 UTC, maekawataiki commented on packages/web/src/components/SketchPad.tsx
>      canvasRef.current?.clear();
こちらは下記の修正で完全に空の状態で SkechPad を閉じると Canvas もクリアされる実装にしたため onClickClear 時は Canvas はまだ更新しない挙動としました。

2024-06-06 01:06 UTC, maekawataiki commented on packages/web/src/components/SketchPad.tsx
> +    // }
すみません、デグレが発生していましたね。
元々 toData() だと fromDataURL() で取り込んだ画像がカウントされないので、入力→開き直す→何も追加せずに閉じるとデータが消える挙動があったので消していましたが toData ではなく isEmpty を使用すると正しい挙動になるため修正しました。

2024-06-06 01:15 UTC, wadabee approved these changes
LGTM!!

2024-06-06 01:16 UTC, merged