Kendraをスケジュールした時刻に作成・削除する
aws-samples/generative-ai-use-cases-jp pull request #529
Opened 2024-06-21 10:13 UTC by cm-yamamoto-hiroki

*Issue #, if available:*

Kendraの利用料を抑えるため、不要な時間帯には稼働を停止させたかったため、Kendraのインデックスを定期的に作成・削除する機能を追加しました

*Description of changes:*

以下を変更しました
- DEPLOY_OPTIONに説明を追加
- cdk.jsonにオプションを追加
- rag.tsに、以下の機能を追加
  - CloudFormationのスタックのParameterを追加（kendraState）
  - スタックのParameterに応じて、Kendraのインデックス・データソースを作成・削除する設定を追加
  - EventBridgeでCRON式を設定し、Step Functionsのステートマシンを実行する設定を追加
  - Step Functionsのステートマシンから、Kendraの起動とデータソースの同期・Kendraの停止を実行するタスク設定を追加
- RAGチャットページからKendraのretrieveを実行した際に、エラーになったら、Kendraのスケジュールを確認するようにメッセージを追加

動作確認として、以下を行いました
- スケジュール機能をオンにした状態で自分のAWSアカウントにデプロイできた
- EventBridge経由で起動・停止が実行され、StepFunctionsのステートマシンが正常に実行され、Kendraが作成・削除された（３回ずつ確認しました）

以下の点は不安に思っている点です、確認いただけると助かります
- rag.tsの変更が大きめで、なにかしら影響がないか
- rag.ts冒頭部分の、定数やクラス定義の書き方・場所が合っているか
- Kendraのデータソースがインデックスに対してaddDepentecyしていた箇所を削除したが、問題ないか
- Kendra検索ページで、Kendraのretrieveがエラーになった際に、どのようなメッセージを表示したらいいかわからなかった。どこかの箇所でエラーハンドリングを追加するべきか

2024-07-04 08:49 UTC, tbrand commented
ありがとうございます！Kendra のコストに悩まれている方が多いので、非常に良いオプションだと思いました！
一度 main ブランチを取り込んでいただいても良いでしょうか？Knowledge Base RAG が追加された影響で rag.ts にもいくつか変更が入っております！

2024-07-04 13:42 UTC, cm-yamamoto-hiroki commented
ご確認ありがとうございます

**追加点**
- mainをマージしました
- 「dataSource.addDependency(index);」をもとに戻しました（復活させました）
  - ない状態でデプロイし、作成・削除をスケジュール実行していると、作成時にエラーになることがありました
  - ある状態でデプロイすると、現状ではエラーが起こっていません

**確認**
以下の設定でデプロイできることを確認しました
"ragEnabled": true,
"kendraIndexScheduleEnabled": true,
"kendraIndexScheduleCreateCron": { "minute": "0", "hour": "23", "month": "*", "weekDay": "SUN-THU" },
"kendraIndexScheduleDeleteCron": { "minute": "0", "hour": "11", "month": "*", "weekDay": "MON-FRI" },

2024-07-05 04:47 UTC, tbrand requested changes
1. 2点インラインコメントいたしました！
2. ルートで `npm run lint` の実行をお願いします！(合わせて CI のエラーの対応もお願いします！)
3. デプロイ時に出る以下の Warninng への対処をお願いします！
```
[WARNING] aws-cdk-lib.aws_stepfunctions.StateMachineProps#definition is deprecated.
  use definitionBody: DefinitionBody.fromChainable()
  This API will be removed in the next major release.
```

2024-07-05 04:47 UTC, tbrand commented on packages/web/src/hooks/useRag.ts
> +- Amazon Kendraインデックス削除としてスケジュールした時刻を過ぎていないか確認する`);
setLoading(false); の追加をお願いします！

2024-07-05 04:47 UTC, tbrand commented on docs/DEPLOY_OPTION.md
> +> [! NOTE]
正しくレンダリングされていないように見えます。`!` の後のスペースが不要？

2024-07-06 06:49 UTC, cm-yamamoto-hiroki commented on packages/web/src/hooks/useRag.ts
> +- Amazon Kendraインデックス削除としてスケジュールした時刻を過ぎていないか確認する`);
追加しました！

2024-07-06 06:49 UTC, cm-yamamoto-hiroki commented on docs/DEPLOY_OPTION.md
> +> [! NOTE]
スペースを削除しました

2024-07-06 11:10 UTC, cm-yamamoto-hiroki commented
ご確認とご指摘ありがとうございます！

> 2点インラインコメントいたしました！

修正いたしました

> ルートで npm run lint の実行をお願いします！(合わせて CI のエラーの対応もお願いします！)

npm run lintを実行しました
エラーになっていた、useRagの2箇所を修正しました

> デプロイ時に出る以下の Warninng への対処をお願いします！

エラーになっていた、Step Functionsの定義を修正しました
definition → definitionBody: stepfunctions.DefinitionBody.fromChainable


**確認**

以下の設定でデプロイできることを確認しました
"ragEnabled": true,
"kendraIndexScheduleEnabled": true,
"kendraIndexScheduleCreateCron": { "minute": "0", "hour": "23", "month": "*", "weekDay": "SUN-THU" },
"kendraIndexScheduleDeleteCron": { "minute": "0", "hour": "11", "month": "*", "weekDay": "MON-FRI" },

2024-07-08 01:51 UTC, tbrand commented
ありがとうございます！あと一点、こちらも同様に definitionBody の対応をお願いいたします！
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/529/files#diff-a0313f61aa583f06ac94fec43a592f06bca05deaa379c8298908b22abcdea762R321

> deployコマンドを実行してしまうと、ログが全部流れてしまうので、
> Warningを確認できる方法をお教えいただけると助かります！

私もデプロイ時にターミナルで目視する以外方法はわからないですね...

2024-07-08 04:21 UTC, cm-yamamoto-hiroki commented
> ありがとうございます！あと一点、こちらも同様に definitionBody の対応をお願いいたします！

修正漏れていて申し訳ありません、修正いたしました！

> 私もデプロイ時にターミナルで目視する以外方法はわからないですね...

cdk synthしたときのログを検索して、warningが出ないことを確認しました

2024-07-08 05:28 UTC, tbrand approved these changes

2024-07-08 05:32 UTC, merged

2024-07-08 05:32 UTC, tbrand commented
ありがとうございます！！！マージさせていただきました！引き続きよろしくお願いいたします！