Llama2 の削除
aws-samples/generative-ai-use-cases-jp pull request #710
Opened 2024-11-12 02:33 UTC by tbrand

## 変更内容の説明
変更内容を詳細に説明して下さい。
既存ユーザーへの影響がある場合 (互換性・デグレ・破壊的変更など) は必ず説明に含めてください。

## チェック項目
- [x] npm run lint を実行した
- [x] 関連するドキュメントを修正した
- [x] 手元の環境で動作確認済み

## 関連する Issue
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/599

2024-11-12 11:53 UTC, kazuhitogo requested changes
すっごく細かいんですが、
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/4992bc89ebebea48ce297ed31bf94e97a8f000c8/packages/types/src/text.d.ts#L71
にある Llama"2" の 2 をこの際消すのはどうでしょうか。

2024-11-13 01:26 UTC, tbrand commented
そちらを含めて、Llama2 という記述はあと 4 箇所あります。SageMaker 経由で利用される可能性があるかなと思ってそれらは残してあるのですが、これらも不要ですか？
- https://github.com/aws-samples/generative-ai-use-cases-jp/blob/remove-llama2/packages/types/src/text.d.ts#L71
- https://github.com/aws-samples/generative-ai-use-cases-jp/blob/remove-llama2/packages/types/src/text.d.ts#L169
- https://github.com/aws-samples/generative-ai-use-cases-jp/blob/remove-llama2/packages/cdk/lambda/utils/models.ts#L47
- https://github.com/aws-samples/generative-ai-use-cases-jp/blob/remove-llama2/packages/cdk/lambda/utils/models.ts#L928-L929

2024-11-13 01:50 UTC, kazuhitogo commented
ありがとうございます。（他にもあったのを見つけてくださってありがとうございます）
SageMaker 経由は残したいですが、2024/11 現在で Llama "2" を使うケースは減っており、3系を使うことが多い＆汎用性が高い"llama"という表現で統一する、でいかがでしょうか。

2024-11-13 02:08 UTC, tbrand commented
こちらで対応の認識あっていますでしょうか？最新コミットを確認していただけますと :pray:
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/710/commits/fd6fdc957fd4bf9d689533af92842fed2879b1fa

2024-11-13 04:54 UTC, kazuhitogo commented
LGTMです！

2024-11-13 04:56 UTC, kazuhitogo approved these changes

2024-11-13 04:56 UTC, merged