[ユースケースビルダー] Amazon Kendra と Knowledge Base の Retrieve に対応
aws-samples/generative-ai-use-cases-jp pull request #760
Opened 2024-12-04 06:09 UTC by tbrand

## 変更内容の説明
Amazon Kendra と Knowledge Base の Retrieve 結果を取得する inputType を作成しました。
これにより、基本的な RAG を含め、社内のデータを活かしたさまざまなユースケースが作成できます。

## チェック項目
- [x] npm run lint を実行した
- [x] 関連するドキュメントを修正した
- [x] 手元の環境で動作確認済み

## 関連する Issue
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/733

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
> +          </div>
コードとコピーボタンが重なっていたので absolute を排除しました。

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
> -          <div className="text-lg font-bold">
新しい入力タイプを追加したことに伴い、ドキュメントを整理しました。大部分を Claude Sonnet 3.5 に書いてもらっています。

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
> +    setText('');
Retrieve 中も強制的に Loading にするために setLoading(true) を追加しました。
また Retrieve 中に前の結果が表示され続けるため、setText('')も追加しています。

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
> +        if (ragEnabled) {
Kendra RAG が有効じゃない場合は retrieve をスキップします。Knowledge Base も同様です。

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
> +        ))}
ragEnabled や ragKnowledgeBaseEnabled が有効ではない場合は warning メッセージを出すようにしています。
![スクリーンショット 2024-12-04 13 47 18](https://github.com/user-attachments/assets/f248d20a-646e-41eb-8334-fae6b5b7698b)

2024-12-04 06:13 UTC, tbrand commented on packages/web/src/utils/UseCaseBuilderUtils.ts
> +          ) === idx
この実装により inputType と label が同じものに関しては同一の入力であると判断するようにしました。例えば無名 text と無名 retrieveKendra があった場合、それらは別の item として扱われます。

2024-12-05 01:31 UTC, wadabee requested changes

2024-12-05 01:31 UTC, wadabee commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx
> +          const res = await retrieveKendra(values[idx]);
retrieveの項目が未入力の状態で実行すると以下のエラーになってずっとローディング中になるので、未入力の制御を行った方が良さそうです。

> {error: "query is not specified"}

2024-12-05 01:31 UTC, wadabee commented on packages/web/src/components/useCaseBuilder/UseCaseBuilderHelp.tsx
> +            です。
「この項目に入力した文言で検索をする」といった説明があった方が良いかなと思いました！
全くの初見だと、この説明とテンプレートサンプルを読んで、まず{{text:質問}}でKendraを検索して{{retrieveKendra:見出し}}にRetrieveした結果が埋め込まれるものと勘違いしてしまいました。

2024-12-05 08:08 UTC, wadabee approved these changes
LGTM!

2024-12-05 08:09 UTC, merged