[WIP] モデルの機能のフラグ管理
aws-samples/generative-ai-use-cases-jp pull request #769
Opened 2024-12-06 06:38 UTC by maekawataiki

## 変更内容の説明
#701 

モデルの機能対応状況（ドキュメントチャット、画像チャット、動画チャット）
https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-supported-models-features.html

## チェック項目
- [x] npm run lint を実行した
- [x] 関連するドキュメントを修正した
- [x] 手元の環境で動作確認済み

## 関連する Issue
関連する Issue を可能な限り挙げてください。

2024-12-09 01:35 UTC, tbrand requested changes
onChangeFiles の uploadFiles に props?.accept が必要ですかね？

2024-12-09 01:35 UTC, tbrand commented on packages/common/package.json
> +    "version": "1.0.0",
ややこしいので version は削除でお願いします！

2024-12-09 01:35 UTC, tbrand commented on packages/cdk/tsconfig.json
> +      "../../node_modules/@types"
TY

2024-12-09 02:08 UTC, maekawataiki commented on packages/common/package.json
> +    "version": "1.0.0",
削除しました

2024-12-10 01:21 UTC, tbrand approved these changes
LGTM!!

2024-12-10 01:21 UTC, merged